# Generated by Django 5.1.4 on 2026-06-21 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('masked_value', models.CharField(blank=True, max_length=512)),
                ('value_hint', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('database_url', 'Database URL'), ('stripe_key', 'Stripe key'), ('github_token', 'GitHub token'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('is_secret', models.BooleanField(default=True)),
                ('is_probeable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('inferred', 'Inferred'), ('probed', 'Probed'), ('done', 'Done')], default='pending', max_length=16)),
                ('source_type', models.CharField(choices=[('paste', 'Pasted'), ('upload', 'Uploaded'), ('repo', 'Repo URL')], default='paste', max_length=16)),
                ('target_environment', models.CharField(default='production', max_length=32)),
                ('config_format', models.CharField(blank=True, max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('correct', 'Correct'), ('suspect', 'Suspect'), ('silently_wrong', 'Silently wrong'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('expected', models.JSONField(blank=True, default=dict)),
                ('reality', models.JSONField(blank=True, default=dict)),
                ('evidence', models.TextField(blank=True)),
                ('blast_radius', models.TextField(blank=True)),
                ('proposed_fix', models.CharField(blank=True, max_length=512)),
                ('confidence', models.FloatField(default=0.0)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finding', to='api.configkey')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.run')),
            ],
        ),
        migrations.AddField(
            model_name='configkey',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='api.run'),
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='api.run')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('line_number', models.PositiveIntegerField()),
                ('usage_kind', models.CharField(blank=True, max_length=64)),
                ('snippet', models.TextField(blank=True)),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sites', to='api.configkey')),
            ],
            options={
                'ordering': ['file_path', 'line_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='configkey',
            unique_together={('run', 'name')},
        ),
    ]
