# Generated by Django 5.1.4 on 2026-06-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_environment', models.CharField(default='any', max_length=32)),
                ('expected_properties', models.JSONField(blank=True, default=dict)),
                ('gates', models.CharField(blank=True, max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('grounded', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='api.configkey')),
            ],
        ),
    ]
