# Generated by Django 5.1.4 on 2026-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='configkey',
            name='secret_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
