# Generated by Django 5.1.4 on 2026-06-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configkey_secret_ciphertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.JSONField(default=dict)),
                ('new_masked', models.CharField(blank=True, max_length=512)),
                ('rationale', models.TextField(blank=True)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='api.configkey')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='api.finding')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='api.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
